### ISSUE TITLE
ES6 syntax used in module

### ISSUE THREAD

**Issue by dallonf** [sindresorhus/p-debounce#1]
This source code uses arrow functions (and possibly other ES6 features, I didn't look too closely), which means it is not compatible with browser environments where IE11 support is required.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446
