### ISSUE TITLE
Rename `leading` to `before`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/p-debounce#10]
To match the wording of https://github.com/sindresorhus/debounce-fn/commit/689f84718afc129895804cbb258ff5c8cd00fdfd

**Comment by sindresorhus** [comment]
Makes sense.

**Comment by Richienb** [comment]
Also affected: https://github.com/sindresorhus/p-wait-for/tree/df45dd3cde7dc49ba00de23de5a92f351f967fe0
