### ISSUE TITLE
Feature Request: CommonJS Support (Drop ESM / Babel Requirement)

### ISSUE THREAD

**Issue by jmealo** [sindresorhus/p-debounce#18]
Hello!

I'm a huge fan of your work and use `got` everywhere I go.

**Use case:** I don't transpile my code or use typescript; I make use `require-in-the-middle` and cannot easily switch my `type` in package.json to `module` nor change all of my `require` to `import`.

I'm not seeing a way to use this module in Node 14 unless my project is 100% ESM and/or using Babel.

Am I missing something?

Thanks for your great work!

**Comment by sindresorhus** [comment]
Then I suggest just staying on the older version. I don't intend to add back CommonJS compatibility. You should prepare for ESM though, as at the end of April, me and many other maintainers intend to move all their packages to ESM: https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77

**Comment by jmealo** [comment]
@sindresorhus: ahhh, that makes sense! Thank you for sharing.

**Comment by sindresorhus** [comment]
You could also use `import(…)` to dynamically import the ESM module into CommonJS. That works.

**Comment by jmealo** [comment]
@sindresorhus: I really appreciate you taking the time to find a workaround given your stance on the subject.
