### ISSUE TITLE
Bad example in README

### ISSUE THREAD

**Issue by thorn0** [sindresorhus/p-debounce#21]
There is this example in README ([link](https://github.com/sindresorhus/p-debounce/blob/main/readme.md#pdebouncepromisefunction_)):
```js
import {setTimeout as delay} from 'timers/promises';
import pDebounce from 'p-debounce';

const expensiveCall = async value => {
	await delay(200);
	return value;
}

const debouncedFn = pDebounce.promise(expensiveCall);

for (const number of [1, 2, 3]) {
	console.log(await debouncedFn(number));
}
//=> 3
//=> 3
//=> 3
```

Actual output:
```
1
2
3
```

**Comment by sindresorhus** [comment]
// @Richienb

**Comment by thorn0** [comment]
It hasn't been fixed. What's the point of using `pDebounce.promise` in this example? It works the same way without debouncing.

**Comment by Richienb** [comment]
This is because `pDebounce.promise` throttles the provided function so that it queues up all of its calls and executes them in order. This means the provided function will never be run twice at the same time. See https://github.com/sindresorhus/promise-fun/issues/15#issuecomment-758577569

**Comment by thorn0** [comment]
This example doesn't try to run it twice at the same.

**Comment by Richienb** [comment]
PR welcome to update the example to demonstrate how it works

**Comment by HuiyingShen96** [comment]
There is also some problem with another example in README ([link](https://github.com/sindresorhus/p-debounce#usage)):
```js
import pDebounce from 'p-debounce';

const expensiveCall = async input => input;

const debouncedFn = pDebounce(expensiveCall, 200);

for (const number of [1, 2, 3]) {
	console.log(await debouncedFn(number));
}
```

Actual output:
```
1
2
3
```
