### ISSUE TITLE
Usage example is wrong

### ISSUE THREAD

**Issue by jeanbmar** [sindresorhus/p-debounce#24]
I was not sure if the example was wrong or if I was just dumb:

```js
import pDebounce from 'p-debounce';

const expensiveCall = async (input) => input;

const debouncedFn = pDebounce(expensiveCall, 200);

for (const number of [1, 2, 3]) {
  console.log(await debouncedFn(number));
}
```

outputs:
```
1
2
3
```

README says:
```
3
3
3
```

Also I'm not sure this example demonstrates the value of the lib. Calling `expensiveCall` alone in the `for` loop would produce the same output.

**Comment by Zhell1** [comment]
seems like the 2 examples are reversed ?

**Comment by Zhell1** [comment]
can confirm, came here to say this

**Comment by Zhell1** [comment]
open a PR to fix the examples, they are both wrong actually

https://github.com/sindresorhus/p-debounce/pull/25
