### ISSUE TITLE
Single call option?

### ISSUE THREAD

**Issue by sprat** [sindresorhus/p-debounce#3]
I would like to debounce a function returning a promise but also limit the concurrent calls of my function to 1. That is, if a previous invocation is still running after the debounce delay is reached, delay again and again... until the last call finish and the debounce delay is expired (no other calls occured during the waiting time).

I know you also developed another module to limit conccurency, but I don't think I can combine it with this one to obtain the behavior I need. In my use case (an async database update), it's important that the last call occur ;)

**Comment by sheerun** [comment]
Same problem, I'd gladly hear some recommendation. In particular I'd like debounced promise where all calls that during time chain is executing cause all running promises to be cancelled and chain is replaced by last running promise. So something like this:

```es6
const expensiveCall = input => new Promise((resolve) => setTimeout(resolve, 1000))

const debouncedFn = pDebounce(expensiveCall, 200, { leading: true });

for (const i of [1, 2, 3]) {
	debouncedFn(i).then(console.log);
}
//=> 3
```

**Comment by sindresorhus** [comment]
I agree, this could be useful. PR welcome if someone can come up with a good option name and behavior.

**Comment by fregante** [comment]
> all running promises to be cancelled

Promises can't be cancelled. `debouncedFn(1)` will still return a promise that needs to be in of 3 states:

- pending
- resolved
- rejected

**Comment by sindresorhus** [comment]
[`AbortController`](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) could potentially be supported.
